package pers.Whyzaa.PlantsVsZobie.Config;

public enum GameState {
	WELCOME,WELCOMETWO,XUNGUAN,GAMEING,GAMEOVER,TUJIAN,CHOICEPLANTS,MAPMOVERIGHT,MAPMOVELEFT,MOVECAOANDCAR,WINNER,LEVEL1,LEVEL2,
	LEVEL3,LEVEL4,LEVEL5,LEVEL6,LEVEL7,LEVEL8,LEVEL9,WIN,LOSE
}
